# Generated by Django 6.0.2 on 2026-03-06 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_core', '0002_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('on_leave', 'On Leave'), ('half_day', 'Half Day'), ('work_from_home', 'Work From Home')], default='present', max_length=20),
        ),
    ]
