# Generated by Django 6.0.2 on 2026-03-10 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems_core', '0004_leavetype_leaverequest_attendance_leave_request_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeaveBalance',
            new_name='LeavesBalance',
        ),
        migrations.RenameModel(
            old_name='LeaveRequest',
            new_name='LeavesRequest',
        ),
        migrations.RenameModel(
            old_name='LeaveType',
            new_name='LeavesType',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='leave_request',
            new_name='leaves_request',
        ),
        migrations.RenameField(
            model_name='leavesbalance',
            old_name='leave_type',
            new_name='leaves_type',
        ),
        migrations.AlterUniqueTogether(
            name='leavesbalance',
            unique_together={('employee', 'leaves_type', 'year')},
        ),
    ]
