# Generated by Django 6.0.2 on 2026-03-10 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems_core', '0005_rename_leavebalance_leavesbalance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leavesrequest',
            old_name='leave_type',
            new_name='leaves_type',
        ),
    ]
