# Generated by Django 6.0.2 on 2026-03-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_core', '0007_payroll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payroll',
            name='salary_deduction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
