# Generated by Django 6.0.2 on 2026-03-12 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_core', '0008_alter_payroll_salary_deduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavestype',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaves_types', to='ems_core.department'),
        ),
    ]
