# Generated by Django 6.0.2 on 2026-03-12 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_core', '0009_leavestype_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_head',
            field=models.OneToOneField(blank=True, limit_choices_to={'user__role': 'manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manage_department', to='ems_core.employee'),
        ),
    ]
